CREATE TABLE `voice_test_results` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`batch_id` text NOT NULL,
	`expected_actor` text NOT NULL,
	`expected_item` text NOT NULL,
	`expected_target` text NOT NULL,
	`expected_phrase` text NOT NULL,
	`transcript` text NOT NULL,
	`duration_ms` integer NOT NULL,
	`local_status` text NOT NULL,
	`local_actor` text,
	`local_item` text,
	`local_target` text,
	`local_actor_match` integer NOT NULL,
	`local_item_match` integer NOT NULL,
	`local_target_match` integer NOT NULL,
	`local_all_match` integer NOT NULL,
	`gemini_status` text NOT NULL,
	`gemini_commands` text NOT NULL,
	`gemini_actor` text,
	`gemini_item` text,
	`gemini_target` text,
	`gemini_confidence` real,
	`gemini_reason` text,
	`gemini_actor_match` integer NOT NULL,
	`gemini_item_match` integer NOT NULL,
	`gemini_target_match` integer NOT NULL,
	`gemini_all_match` integer NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
